### ISSUE TITLE
Units for pixel sizes in translation are incorrect

### ISSUE THREAD

**Issue by evamaxfield** [AllenCellModeling/czi-to-ome-xslt#12]
We want to save pixel values in units of micrometers translation returns something else.....

Take the file `s_3_t_1_c_3_z_5.czi` and convert with translation and see that the metadata for pixel sizes is incorrect: 
![image](https://user-images.githubusercontent.com/17132317/130531768-47821c09-0611-42e8-937b-9edd7ef47fd0.png)

```
<Pixels BigEndian="false" DimensionOrder="XYCZT" ID="Pixels:0" Interleaved="false" PhysicalSizeX="0.908210704883533" PhysicalSizeXUnit="µm" PhysicalSizeY="0.908210704883533" PhysicalSizeYUnit="µm" SignificantBits="14" SizeC="3" SizeT="1" SizeX="7705" SizeY="6183" SizeZ="1" Type="uint16">
```

They should be `9.08...`

**Comment by MatteBailey** [comment]
@JacksonMaxfield, can you double check that this was with `s_3_t_1_c_3_z_5.czi`? I'm seeing very different data for that file.

**Comment by evamaxfield** [comment]
Ahhhh sorry! It was `"aicsimageio/tests/resources/variable_scene_shape_first_scene_pyramid.czi"`

**Comment by evamaxfield** [comment]
Interesting I just checked `OverviewScan.czi` and the physical pixel sizes are saved out correctly....

**Comment by MatteBailey** [comment]
@heeler, do you have any memory of the origins of the logic in the original code to handle pixel sizes, back in April 2020? See here:
https://github.com/AllenCellModeling/czi-to-ome-xslt/blob/b7c6be409c91a0a4814d8bfae020ae32795bb0f8/aicsxslt/xslt/Image.xsl#L50-L59

I ended up copying this block elsewhere, but now that I'm looking at it more closely, the logic for when the value is less than 1E-5 doesn't make sense to me. No worries if you don't recall!

**Comment by MatteBailey** [comment]
@JacksonMaxfield, is it a requirement that we always save pixel size in µm? That would potentially mean adding a lot of unit conversion to the XSLT, which sounds unpleasant.

**Comment by MatteBailey** [comment]
Also, since the metadata for pixel sizes in `variable_scene_shape_first_scene_pyramid.czi` looks like this:
```xml
<Items>
    <Distance Id="X">
        <Value>9.0821070488353288E-07</Value>
        <DefaultUnitFormat>µm</DefaultUnitFormat>
    </Distance>
    <Distance Id="Y">
        <Value>9.0821070488353288E-07</Value>
        <DefaultUnitFormat>µm</DefaultUnitFormat>
    </Distance>
</Items>
```
We would expect the relevant attributes in the OME XML to look like below, yeah?
```
PhysicalSizeX="9.0821070488353288E-07" PhysicalSizeXUnit="µm" PhysicalSizeY="9.0821070488353288E-07" PhysicalSizeYUnit="µm"
```

**Comment by evamaxfield** [comment]
I don't think there is a requirement just the expectation of micrometers. That said, we can probably just solve this if we adopt [pint](https://pint.readthedocs.io/en/stable/) on the `aicsimageio` side. The reason we have this issue is because on the `AICSImage.physical_pixel_sizes` we do try to get it to micrometers but we don't explicity attach units.... with pint we can just attach the units and let the user do whatever they want AND specific to this issue, the XSLT and metadata can stay untouched.

**Comment by heeler** [comment]
If memory serves the systems I saw examples of all returned something different. Some returned meters some returned um etc. The thinking with that block was just to consistently return meters but I likely should have also overwritten the um units and forgot. I didn't get a comprehensive answer from microscopy at the time so it was a "first pass" approach.

**Comment by MatteBailey** [comment]
The CZI docs about `DefaultUnitFormat` say the following:
> If the format parameter is not specified in a UnitItem method that expects a format value,
            then this DefaultUnitFormat is used.
            Note that this is "just a hint" which unit of measurement should be used to present
            the distance value to the user, **it does not change the unit of the Value-field (which is
            always meters, irrespective of the content of this element**).

So if we have a case like this:
```xml
<Items>
    <Distance Id="X">
        <Value>9.0821070488353288E-07</Value>
        <DefaultUnitFormat>µm</DefaultUnitFormat>
    </Distance>
    <Distance Id="Y">
        <Value>9.0821070488353288E-07</Value>
        <DefaultUnitFormat>µm</DefaultUnitFormat>
    </Distance>
</Items>
```
It sounds like `Value` might actually be in meters. I'll see if Tim knows anything about this.

**Comment by heeler** [comment]
That seems to explain what is displayed in the metadata block. Value in meters and a preferred unit to display it in. It seems odd but at least it explains what is displayed.

**Comment by cfrick13** [comment]
I can confirm that the values are in meters.
